# Generated by Django 4.0.4 on 2022-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
