# Generated by Django 4.0.4 on 2022-07-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
