# Generated by Django 4.0.4 on 2022-06-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
