# Generated by Django 4.0.4 on 2022-06-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_remove_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='blank', upload_to='static/avatars'),
            preserve_default=False,
        ),
    ]
