# Generated by Django 4.0.4 on 2022-06-03 14:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0007_userfollowing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollowing',
            new_name='Following',
        ),
    ]
