# Generated by Django 4.0.4 on 2022-06-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_rename_userfollowing_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='user_id',
            new_name='user',
        ),
    ]
