# Generated by Django 4.0.4 on 2022-06-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_rename_following_user_id_following_following_user_and_more'),
    ]
