# Generated by Django 4.0.4 on 2022-06-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_index_together_recipient_unread'),
        ('personal', '0011_profile_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notifications.notification',),
        ),
    ]
