# Generated by Django 4.0.4 on 2022-06-17 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_notificationproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_request_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
